version: '3'

services:
  webapp:
    container_name: webapp
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
volumes:
  postgres_data: